### PR TITLE
support chunkFilename rename

### PR DESCRIPTION
**Pull request by lonelyclick**
- support chunkFIlename rename
- My atom deleted some useless space

#42

### CODE REVIEW

**Comment by halt-hammerzeit** [comment]
Ok, I'll merge it if you change `chunkFilename` to `chunkInfoFilename` everywhere in your code.

**Comment by lonelyclick** [comment]
Wait a minute, there are bugs

**Comment by lonelyclick** [comment]
Done, Thanks

**Comment by lonelyclick** [comment]
webpack-isomorphic-tools and universal-webpack I used it all.

Very obvious, universal-webpack is better, thank you very much

**Pull request merged**
